### ISSUE TITLE
Crash when accessing "Job"

### ISSUE THREAD

**Issue by iz3man** [seeul8er/RepPanel_ESP32#10]
Soldered everyting together yesterday and installed latest precompiled firmware to my Wemos32. 
Everything worked instantly. I can connect to the printer and send G commands etc.

But when I press "Job" this leads to an instand reboot of the ESP.

See attached video: https://youtu.be/_Eae3WFpU4Y

**Comment by seeul8er** [comment]
How many jobs are listed in the root directory?

**Comment by iz3man** [comment]
28

**Comment by seeul8er** [comment]
There you have it. Because we a running low on RAM, [RepPanel is currently limited to 16 items per listing](https://github.com/seeul8er/RepPanel_ESP32#known-limitations). I suggest you reduce your item count per directory (<16) by adding more subfolders.

**Comment by iz3man** [comment]
That's a shame. Should have read the readme more carefully. This renders the device pretty useless. putting everything into subdirectories makes it a mess. And if I got 16 subfolders I need subfolders for subfolders?
Any solution for this? Other ESP?

**Comment by seeul8er** [comment]
Yes. RepPanel can list 16 entries per directory (folders + files <=16)
Right now I have no ambition to squeeze more out of it since the system will get more unstable when bigger parts of the screen need an update (requires more RAM).
I have some ideas for [a new/custom board that features an ESP32 with attached 4/8MB of external RAM](https://docs.google.com/forms/d/e/1FAIpQLSc41e0SKuG6xnuFPz0I5em8UYw0sTvzpZe8-aQhP_QksgwWyg/viewform?usp=sf_link). That would eliminate most of the limitations we have with the DEV-Board based setups. However, as of today, only a single person showed interest so I am currently not pushing into that direction, since it also requires some $/€/time invest from my side to get it working.
