### ISSUE TITLE
wiring issue

### ISSUE THREAD

**Issue by cdedwards** [seeul8er/RepPanel_ESP32#2]
Could you maybe give actual pin numbers on the tft panel in the following diagram?
http://prntscr.com/smmjlo

The ESP32 device I have and the nice ESP32_ Pinout diagram do not match at all. As well, the wiring pictures seem to be slightly out of sync compared to the diagrams. for example, the brown wire on the TFT picture goes to a NON ground pin on the ESP32.. Whereas the green wire, is hooked up to a "ground" on the ESP32, is not hooked to a ground on the TFT.

**Comment by seeul8er** [comment]
The picture with the wiring relates to a [ESP32 DoIt Dev kit](https://i2.wp.com/randomnerdtutorials.com/wp-content/uploads/2018/08/ESP32-DOIT-DEVKIT-V1-Board-Pinout-36-GPIOs-updated.jpg?ssl=1). 
I think I will remove the pictures since they can cause more confusion than help clarifying the issue. There are just too many different board layouts for ESP32 dev kits.

I'll update the table as well to match with the ER-TFT module. [Check out page 11 on the docs](https://www.buydisplay.com/download/manual/ER-TFTM035-6_Datasheet.pdf) for details till then.

**Comment by seeul8er** [comment]
Updated README
